age = input("Введите свой возраст: ")
print(age)
gender = input("Введите свой пол: ")
print(gender)
name = input("Введите своё имя: ")
print(name)
city = input("Введите свой город: ")
print(city)
grade = input("Введите свой класс: ")
print(grade)